@startuml

class Project

class EditorViewModel
{
    + CreateCommand
    + ExportCommand
    + LoadCommand
    + SaveCommand
    + UndoCommand
    + RedoComamnd
}

class Editor
{
    + Create()
    + Export()
    + Load()
    + Save()
    + Undo()
    + Redo()
}

interface ILoadService
interface IExportService
interface ISaveService
interface ICreateService

EditorViewModel o-- Editor
EditorViewModel o-- ProjectViewModel
EditorState o-- ILoadService
EditorState o-- IExportService
EditorState o-- ISaveService
EditorState o-- ICreateService
IExportService o-- Serializer
Project o-- CommandHistory

ProjectData <-- ISaveService
ProjectData <-- ILoadService

Editor o-- EditorState
EditorState <|-- Empty
EditorState <|-- New
EditorState <|-- Clean
EditorState <|-- Dirty
EditorState <|-- SettingsBroken
New o-- Project
Clean o-- Project
Dirty o-- Project
SettingsBroken o-- Project

Project o-- ProjectSettings
Project o-- DependencyManager
Project o-- StateRoot

EditorViewModel o-- StateRootViewModel

@enduml